routes/web.php
<?php

use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;
use phpDocumentor\Reflection\Types\Resource_;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('home');
Route::get('/blogs/{post}', [FrontendController::class, 'show'])->name('blogs.show');
Route::get('blogs/category/{category}', [FrontendController::class, 'category'])->name('blogs.category');
Route::get('blogs/tags/{tag}', [FrontendController::class, 'tag'])->name('blogs.tag');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';


//Application Routes

//Used raw url for categories.destroy


//Route Grouping
Route::middleware(['auth'])->group(function () {
    Route::resource('categories', CategoriesController::class);
    Route::resource('tags', TagsController::class);
    Route::post('posts/{post}/comments', [CommentsController::class, 'store'])->name('posts.create-comments');
    Route::post('posts/{post}/comments/{comment}/replies', [CommentsController::class, 'storeReply'])->name('posts.comments.replies');
    Route::get('posts/comments-requests', [CommentsController::class, 'requestedComments'])->name('posts.comments-requests');
    Route::put('posts/comments/{comment}/approve', [CommentsController::class, 'approveComment'])->name('posts.approve-comment');
    Route::put('posts/comments/{comment}/disapprove', [CommentsController::class, 'disapproveComment'])->name('posts.disapprove-comment');
    Route::delete('posts/trash/{post}', [PostsController::class, 'trash'])->name('posts.trash');
    Route::get('posts/trashed', [PostsController::class, 'trashed'])->name('posts.trashed');
    Route::put('posts/restore/{post}', [PostsController::class, 'restore'])->name('posts.restore');
    Route::get('posts/drafts', [PostsController::class, 'drafts'])->name('posts.drafts');
    Route::get('/posts/requests', [PostsController::class, 'requests'])->name('posts.approval-requests');
    Route::put('/posts/drafts/{post}/draft', [PostsController::class, 'draftPost'])->name('posts.draft-post');
    Route::put('posts/requests/{post}/approve', [PostsController::class, 'approveRequest'])->name('posts.approve-request');
    Route::put('posts/requests/{post}/disapprove', [PostsController::class, 'disapproveRequest'])->name('posts.disapprove-request');
    Route::put('posts/drafts/{post}/publish', [PostsController::class, 'publishDraft'])->name('posts.publish-draft');
    Route::resource('posts', PostsController::class);
});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('/users', [UsersController::class, 'index'])->name('users.index');
    Route::put('/users/{user}/make-admin', [UsersController::class, 'makeAdmin'])->name('users.make-admin');
    Route::put('/users/{user}/revoke-admin', [UsersController::class, 'revokeAdmin'])->name('users.revoke-admin');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Thomaswelton\LaravelGravatar\Facades\Gravatar;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    const ADMIN = 'admin';
    const AUTHOR = 'author';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function isAdmin(): bool
    {
        return $this->role === User::ADMIN;
    }

    public function getGravatarImageAttribute(): string
    {
        return Gravatar::src($this->email, 80);
    }
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function index()
    {
        $users = User::paginate(10);
        return view('users.index', compact(['users']));
    }


    public function makeAdmin(User $user)
    {
        $user->update(['role' => User::ADMIN]);
        session()->flash('success', $user->name . ' has been assigned admin role!');
        return redirect(route('users.index'));
    }

    public function revokeAdmin(User $user)
    {
        $user->update(['role' => User::AUTHOR]);
        session()->flash('success', $user->name . ' has been revoked from admin role!');
        return redirect(route('users.index'));
    }
}

resources/views/users/index.blade.php
@extends('layouts.admin-panel.app')

@section('content')

    <div class="card">
        <div class="card-header m-0">
            <h2>Users</h2>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Image</th>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Posts</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($users as $user)
                        <tr>
                            <td><img src="{{ $user->gravatar_image }}" width="80" alt=""></td>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->posts->count() }}</td>
                            <td>
                                @if (!$user->isAdmin())
                                    <form action="{{ route('users.make-admin', $user->id) }}" method="POST">
                                        @csrf
                                        @method('PUT')

                                        <button type="submit" class="btn btn-sm btn-outline-success">Make Admin</button>
                                    </form>
                                @else
                                    <form action="{{ route('users.revoke-admin', $user->id) }}" method="POST">
                                        @csrf
                                        @method('PUT')

                                        <button type="submit" class="btn btn-sm btn-outline-danger">Revoke Admin</button>
                                    </form>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>


    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">

            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" id="deletepost" method="POST">
                    @csrf
                    @method('DELETE')
                    <div class="modal-body">
                        Are you sure you want to delete this post?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-outline-danger">Delelte Post</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {{ $users->links('') }}
@endsection

@section('page-level-scripts')
    <script>
        function displayModal(postId) {
            var url = "/posts/trash/" + postId;
            $("#deletepost").attr('action', url);
        }
    </script>
@endsection