routes/web.php
<?php

use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;
use phpDocumentor\Reflection\Types\Resource_;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('home');
Route::get('/blogs/{post}', [FrontendController::class, 'show'])->name('blogs.show');
Route::get('blogs/category/{category}', [FrontendController::class, 'category'])->name('blogs.category');
Route::get('blogs/tags/{tag}', [FrontendController::class, 'tag'])->name('blogs.tag');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';


//Application Routes

//Used raw url for categories.destroy


//Route Grouping
Route::middleware(['auth'])->group(function () {
    Route::resource('categories', CategoriesController::class);
    Route::resource('tags', TagsController::class);
    Route::post('posts/{post}/comments', [CommentsController::class, 'store'])->name('posts.create-comments');
    Route::post('posts/{post}/comments/{comment}/replies', [CommentsController::class, 'storeReply'])->name('posts.comments.replies');
    Route::get('posts/comments-requests', [CommentsController::class, 'requestedComments'])->name('posts.comments-requests');
    Route::put('posts/comments/{comment}/approve', [CommentsController::class, 'approveComment'])->name('posts.approve-comment');
    Route::put('posts/comments/{comment}/disapprove', [CommentsController::class, 'disapproveComment'])->name('posts.disapprove-comment');
    Route::delete('posts/trash/{post}', [PostsController::class, 'trash'])->name('posts.trash');
    Route::get('posts/trashed', [PostsController::class, 'trashed'])->name('posts.trashed');
    Route::put('posts/restore/{post}', [PostsController::class, 'restore'])->name('posts.restore');
    Route::get('posts/drafts', [PostsController::class, 'drafts'])->name('posts.drafts');
    Route::get('/posts/requests', [PostsController::class, 'requests'])->name('posts.approval-requests');
    Route::put('/posts/drafts/{post}/draft', [PostsController::class, 'draftPost'])->name('posts.draft-post');
    Route::put('posts/requests/{post}/approve', [PostsController::class, 'approveRequest'])->name('posts.approve-request');
    Route::put('posts/requests/{post}/disapprove', [PostsController::class, 'disapproveRequest'])->name('posts.disapprove-request');
    Route::put('posts/drafts/{post}/publish', [PostsController::class, 'publishDraft'])->name('posts.publish-draft');
    Route::resource('posts', PostsController::class);
});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('/users', [UsersController::class, 'index'])->name('users.index');
    Route::put('/users/{user}/make-admin', [UsersController::class, 'makeAdmin'])->name('users.make-admin');
    Route::put('/users/{user}/revoke-admin', [UsersController::class, 'revokeAdmin'])->name('users.revoke-admin');
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Post extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $guarded = ['id'];
    protected $dates = ['published_at'];


    public function getImagePathAttribute()
    {
        return 'storage/' . $this->image;
    }

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }
    public function hasTag(int $tag_id): bool
    {
        return in_array($tag_id, $this->tags->pluck('id')->toArray());
    }

    public function deleteImage()
    {
        Storage::delete($this->image);
    }

    /**
     * Query Scopes
     */

    public function scopePublished($query)
    {
        return $query->where('published_at', '<=', now())
            ->where('approved_at', '<=', now());
    }

    public function scopeDrafted($query)
    {
        return $query->where('published_at', '>', now())
            ->orWhere('published_at', '=', NULL);
    }

    public function scopeSearch($query)
    {
        $search = request('search');
        if ($search) {
            return $query->where('title', 'like', "%$search%");
        }
        return $query;
    }

    public function scopeRequested($query)
    {
        return $query->where('approved_at', NULL);
    }

    public function getParentComments()
    {
        $comments = Comment::where('parent_id', NULL)->get();
        return $comments;
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Posts\CreatePostRequest;
use App\Http\Requests\Posts\UpdatePostRequest;
use App\Models\Category;
use App\Models\Post;
use App\Models\Tag;
use Illuminate\Http\Request;

class PostsController extends Controller
{

    public function __construct()
    {
        $this->middleware(['validateAuthor'])->only('edit', 'update', 'destroy', 'trash');
        $this->middleware(['verifyCategory', 'verifyTag'])->only('create', 'store');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (auth()->user()->isAdmin()) {
            $posts = Post::published()->paginate(3);
        } else {
            $posts = Post::published()->where('user_id', auth()->id())->paginate(10); //to do: using scope
        }

        return view('posts.index', compact(['posts']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('posts.create', compact(['categories', 'tags']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostRequest $request)
    {
        $image = $request->file('image')->store('images/posts');
        $post = Post::create([
            'title' => $request->title,
            'excerpt' => $request->excerpt,
            'content' => $request->content,
            'category_id' => $request->category_id,
            'user_id' => auth()->id(),
            'image' => $image,
            'published_at' => $request->published_at,

        ]);

        $post->tags()->attach($request->tags);
        session()->flash('success', 'A request to approve your post has been sent to the admin');
        return redirect(route('posts.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {

        $categories = Category::all();
        $tags = Tag::all();
        return view('posts.edit', compact(['post', 'categories', 'tags']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, Post $post)
    {
        $data = $request->only('title', 'excerpt', 'content', 'published_at', 'category_id');

        if ($request->hasFile('image')) {
            $image = $request->image->store('images/posts');
            $data['image'] = $image;
            $post->deleteImage();
        }

        $post->update($data);

        $post->tags()->sync($request->tags);
        session()->flash('success', 'Post update successfully');
        return redirect(route('posts.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) //we are not using Post $post here because route-model binding fails
    {
        $post = Post::onlyTrashed()->findOrFail($id);
        $post->deleteImage();
        $post->forceDelete();
        session()->flash('success', 'Post deleted successfully!');
        return redirect(route('posts.trashed'));
    }

    public function trash(Post $post)
    {
        $post->delete();
        session()->flash('success', 'Post trashed');
        return redirect(route('posts.index'));
    }

    public function trashed()
    {
        $trashed = Post::onlyTrashed()->paginate(10);
        return view('posts.trashed', ['posts' => $trashed]);
    }

    public function restore($id)
    {
        $trashedPost = Post::onlyTrashed()->findOrFail($id);
        $trashedPost->restore();
        session()->flash('success', 'Post restored succesfully!');
        return redirect(route('posts.index'));
    }

    public function drafts()
    {
        $drafts = Post::drafted()->paginate(3);
        return view('posts.drafts', ['posts' => $drafts]);
    }
    public function draftPost(Post $post)
    {
        $post->update(['published_at' => NULL]);
        session()->flash('success', 'Post drafted successfully!');
        return redirect(route('posts.index'));
    }
    public function publishDraft(Post $post)
    {

        $post->update(['published_at' => now()]);
        session()->flash('success', 'Post published successfully!');
        return redirect(route('posts.index'));
    }

    public function requests()
    {
        $posts = Post::requested()->paginate(3);
        return view('posts.requests', compact('posts'));
    }

    public function approveRequest(Post $post)
    {
        $post->update(['approved_at' => now()]);

        session()->flash('success', 'Post approved!');
        return redirect(route('posts.index'));
    }
    public function disapproveRequest(Request $request, Post $post)
    {
        $post->update(['approved_at' => NULL]);
        $post->update(['disapproval_reason' => $request->reason]);
        session()->flash('success', 'Post disapproved!');
        return redirect(route('posts.approval-requests'));
    }
}

resources/views/posts/create.blade.php
@extends('layouts.admin-panel.app')

@section('page-level-styles')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.css"
        integrity="sha512-CWdvnJD7uGtuypLLe5rLU3eUAkbzBR3Bm1SFPEaRfvXXI2v2H5Y0057EMTzNuGGRIznt8+128QIDQ8RqmHbAdg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
@endsection


@section('content')



    <div class="card">
        <div class="card-header m-0">
            Add a new post
        </div>
        <div class="card-body">
            <form action="{{ route('posts.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" name="title" id="title" class="form-control @error('title') is-invalid @enderror"
                        value="{{ old('title') }}" placeholder="Enter post title">
                    @error('title')
                        <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="excerpt">Excerpt</label>
                    <input type="text" name="excerpt" id="excerpt"
                        class="form-control @error('excerpt') is-invalid @enderror" value="{{ old('excerpt') }}"
                        placeholder="Enter post excerpt">
                    @error('excerpt')
                        <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="content">Content</label>
                    <input id="content" type="hidden" name="content" value="{{ old('content') }}">
                    <trix-editor input="content">
                    </trix-editor>
                    @error('content')
                        <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="category">Category</label>
                    <select name="category_id" id="category_id" class="select2 form-control">
                        <option></option> {{-- blank option for placeholder --}}
                        @foreach ($categories as $category)
                            @if ($category->id == old('category_id'))
                                <option value="{{ $category->id }} " selected>{{ $category->name }}</option>
                            @else
                                <option value="{{ $category->id }}"> {{ $category->name }} </option>
                            @endif
                        @endforeach
                    </select>
                    @error('category')
                        <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="tag">Tag</label>
                    <select name="tags[]" id="tag_id" class="select2 form-control" multiple>
                        <option></option> {{-- blank option for placeholder --}}
                        @foreach ($tags as $tag)
                            {{-- @if ($tag->id == old('tag_id'))
                                <option value="{{ $tag->id }} " selected>{{ $tag->name }}</option>
                            @else
                                <option value="{{ $tag->id }}"> {{ $tag->name }} </option>
                            @endif --}}
                            <option value=" {{ $tag->id }} "
                                {{ old('tags') && in_array($tag->id, old('tags')) ? 'selected' : '' }}>
                                {{ $tag->name }}
                            </option>
                        @endforeach
                    </select>

                    @error('tag')
                        <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="published_at">Published At</label>
                    <input type="text" name="published_at" id="published_at"
                        class="form-control @error('published_at') is-invalid @enderror"
                        value="{{ old('published_at') }}" placeholder="Enter post published_at">
                    @error('published_at')
                        <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="file" class="form-control @error('image') is-invalid @enderror" name="image" id="image">
                    @error('image')
                        <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
                <button type="submit" class="btn btn-outline-success">Submit</button>
            </form>
        </div>
    </div>
@endsection


@section('page-level-scripts')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"
        integrity="sha512-/1nVu72YEESEbcmhE/EvjH/RxTg62EKvYWLG3NdeZibTCuEtW5M4z3aypcvsoZw03FAopi94y04GhuqRU9p+CQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>
        $('.select2').select2({
            placeholder: 'Select an option',
        });
        flatpickr("#published_at", {
            enableTime: true,
            dateFormat: "Y-m-d H:i",
            minDate: new Date(),
        });
    </script>
@endsection

resources/views/posts/drafts.blade.php
@extends('layouts.admin-panel.app')

@section('content')



    <div class="d-flex justify-content-end mb-3">
        <a href="{{ route('posts.create') }}" class="btn btn-outline-primary">Add Post</a>
    </div>
    <div class="card">
        <div class="card-header m-0">
            <h2>Posts</h2>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Image</th>
                        <th scope="col">Title</th>
                        <th scope="col">Excerpt</th>
                        <th scope="col">Category</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($posts as $post)
                        <tr>
                            <td><img src="{{ asset($post->image_path) }}" width="140" alt=""></td>
                            <td>{{ $post->title }}</td>
                            <td>{{ $post->excerpt }}</td>
                            <td>{{ $post->category->name }}</td>
                            <td><a href="{{ route('posts.edit', $post->id) }}" class="btn btn-sm btn-primary">
                                    Edit</a>
                                <form action="{{ route('posts.publish-draft', $post->id) }}" method="POST">
                                    @csrf
                                    @method('PUT')

                                    <button type="submit" class="btn btn-sm btn-outline-success">Publish Post</button>
                                </form>
                                <button type="button" class="btn btn-sm btn-danger" data-toggle="modal"
                                    data-target="#deleteModal" onclick="displayModal({{ $post->id }})">Trash
                                </button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>


    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">

            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" id="deletepost" method="POST">
                    @csrf
                    @method('DELETE')
                    <div class="modal-body">
                        Are you sure you want to trash this post?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-outline-danger">Trash Post</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {{ $posts->links('') }}
@endsection

@section('page-level-scripts')
    <script>
        function displayModal(postId) {
            var url = "/posts/trash/" + postId;
            $("#deletepost").attr('action', url);
        }
    </script>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.admin-panel.app')

@section('page-level-styles')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.css"
        integrity="sha512-CWdvnJD7uGtuypLLe5rLU3eUAkbzBR3Bm1SFPEaRfvXXI2v2H5Y0057EMTzNuGGRIznt8+128QIDQ8RqmHbAdg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
@endsection


@section('content')



    <div class="card">
        <div class="card-header m-0">
            Add a new post
        </div>
        <div class="card-body">
            <form action="{{ route('posts.update', $post->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" name="title" id="title" class="form-control @error('title') is-invalid @enderror"
                        value="{{ old('title', $post->title) }}" placeholder="Enter post title">
                    @error('title')
                        <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="excerpt">Excerpt</label>
                    <input type="text" name="excerpt" id="excerpt"
                        class="form-control @error('excerpt') is-invalid @enderror"
                        value="{{ old('excerpt', $post->excerpt) }}" placeholder="Enter post excerpt">
                    @error('excerpt')
                        <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="content">Content</label>
                    <input id="content" type="hidden" name="content" value="{{ old('content', $post->content) }}">
                    <trix-editor input="content">
                    </trix-editor>
                    @error('content')
                        <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="category">Category</label>
                    <select name="category_id" id="category_id" class="select2 form-control">
                        <option></option> {{-- blank option for placeholder --}}
                        @foreach ($categories as $category)
                            @if ($category->id == old('category_id', $post->category_id))
                                <option value="{{ $category->id }} " selected>{{ $category->name }}</option>
                            @else
                                <option value="{{ $category->id }}"> {{ $category->name }} </option>
                            @endif
                        @endforeach
                    </select>
                    @error('category')
                        <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="tag">Tag</label>
                    <select name="tags[]" id="tag_id" class="select2 form-control" multiple>
                        <option></option> {{-- blank option for placeholder --}}
                        @foreach ($tags as $tag)
                            @if (( old('tags') && (in_array($tag->id,old('tags'))) || $post->hasTag($tag->id) ))
                            <option value="{{ $tag->id }} " selected>{{ $tag->name }}</option>
                        @else
                            <option value="{{ $tag->id }} ">{{ $tag->name }}</option>
                        @endif
                        @endforeach
                    </select>

                    @error('tag')
                        <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="published_at">Published At</label>
                    <input type="text" name="published_at" id="published_at"
                        class="form-control @error('published_at') is-invalid @enderror"
                        value="{{ old('published_at', $post->published_at) }}" placeholder="Enter post published_at">
                    @error('published_at')
                        <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="file" class="form-control @error('image') is-invalid @enderror" name="image" id="image">
                    @error('image')
                        <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
                <button type="submit" class="btn btn-outline-success">Submit</button>
            </form>
        </div>
    </div>
@endsection


@section('page-level-scripts')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"
        integrity="sha512-/1nVu72YEESEbcmhE/EvjH/RxTg62EKvYWLG3NdeZibTCuEtW5M4z3aypcvsoZw03FAopi94y04GhuqRU9p+CQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>
        $('.select2').select2({
            placeholder: 'Select an option',
        });
        flatpickr("#published_at", {
            enableTime: true,
            dateFormat: "Y-m-d H:i",
            minDate: new Date(),
        });
    </script>
@endsection

resources/views/posts/requests.blade.php
@extends('layouts.admin-panel.app')

@section('content')



    <div class="d-flex justify-content-end mb-3">
        <a href="{{ route('posts.create') }}" class="btn btn-outline-primary">Add Post</a>
    </div>
    <div class="card">
        <div class="card-header m-0">
            <h2>Posts</h2>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Image</th>
                        <th scope="col">Title</th>
                        <th scope="col">Excerpt</th>
                        <th scope="col">Category</th>
                        <th scope="col">Prior disapproval reason</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($posts as $post)
                        <tr>
                            <td><img src="{{ asset($post->image_path) }}" width="140" alt=""></td>
                            <td>{{ $post->title }}</td>
                            <td>{{ $post->excerpt }}</td>
                            <td>{{ $post->category->name }}</td>
                            <td>{{ $post->disapproval_reason }}</td>
                            <td>
                                <form action="{{ route('posts.approve-request', $post->id) }}" method="POST">
                                    @csrf
                                    @method('PUT')

                                    <button type="submit" class="btn btn-sm btn-primary">Approve</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>


    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">

            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" id="deletepost" method="POST">
                    @csrf
                    @method('DELETE')
                    <div class="modal-body">
                        Are you sure you want to delete this post?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-outline-danger">Delelte Post</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {{ $posts->links('vendor.pagination.bootstrap-4') }}
@endsection

@section('page-level-scripts')
    <script>
        function displayModal(postId) {
            var url = "/posts/trash/" + postId;
            $("#deletepost").attr('action', url);
        }
    </script>
@endsection